// ============================================================
// DATA SAMPEL AWAL PLATFORM BAGIPROMPT.ID
// ============================================================
const SAMPLE_PROMPTS = [
  {
    id: "p1",
    title: "Kota Futuristik Malam Hari",
    category: "Midjourney",
    description: "Prompt untuk menghasilkan visual kota cyberpunk dengan pencahayaan neon dramatis.",
    promptText: "Cyberpunk Tokyo street at night, neon glowing signs, rain reflection on asphalt, flying futuristic cars, high detail, volumetric lighting, unreal engine 5 render, cinematic composition, 8k resolution --ar 16:9 --style raw --v 6.0",
    imageUrl: "assets/img/cyberpunk-city.jpg",
    tags: ["cyberpunk", "neon", "tokyo", "scifi"],
    creatorId: "u1",
    creatorName: "Ahmad Dani",
    uploadDate: "12 Jan 2026",
    viewCount: 1200,
    copyCount: 340,
    isPublished: true,
    isVerified: true,
    status: "Aktif"
  },
  {
    id: "p2",
    title: "Logo Startup Teknologi Minimalis",
    category: "DALL-E",
    description: "Pembuatan aset logo korporat bertema kecerdasan buatan berbentuk sirkuit otak.",
    promptText: "A minimal modern vector logo for an artificial intelligence startup, clean lines, geometric shape resembling both a brain and a circuit board, vibrant indigo accent on pure white background, corporate design style, flat vector, Behance portfolio showcase",
    imageUrl: "assets/img/startup-logo.jpg",
    tags: ["logo", "minimalist", "startup", "circuit"],
    creatorId: "u2",
    creatorName: "Siti Rahma",
    uploadDate: "15 Jan 2026",
    viewCount: 890,
    copyCount: 156,
    isPublished: true,
    isVerified: true,
    status: "Aktif"
  },
  {
    id: "p3",
    title: "Deskripsi Produk Jam Tangan Mewah",
    category: "ChatGPT",
    description: "Kerangka salinan iklan jam tangan titanium mewah untuk target pasar eksekutif.",
    promptText: "Tuliskan deskripsi produk yang elegan dan persuasif untuk jam tangan mewah pria bernama 'Aethelgard Chronograph'. Target audiens adalah eksekutif muda sukses. Fokus pada detail pengerjaan tangan, material titanium, daya tahan air, dan prestise yang dihadirkannya. Gunakan gaya bahasa profesional, mewah, namun tetap modern.",
    imageUrl: "assets/img/chatgpt-watch.jpg",
    tags: ["copywriting", "luxury", "watch", "persuasive"],
    creatorId: "u3",
    creatorName: "Budi Santoso",
    uploadDate: "18 Jan 2026",
    viewCount: 450,
    copyCount: 112,
    isPublished: true,
    isVerified: false,
    status: "Aktif"
  },
  {
    id: "p4",
    title: "Potret Fantasi Karakter Elf",
    category: "Stable Diffusion",
    description: "Menghasilkan potret fantasi detail tinggi dengan gaun zirah keemasan.",
    promptText: "Ethereal female elf portrait, silver hair braided with glowing leaves, deep emerald eyes, soft dynamic natural lighting, photorealistic skin texture, highly detailed armor with gold filigree, cinematic depth of field, artstation trending, masterpiece, 8k",
    imageUrl: "assets/img/elf-portrait.jpg",
    tags: ["fantasy", "elf", "portrait", "realism"],
    creatorId: "u1",
    creatorName: "Ahmad Dani",
    uploadDate: "20 Jan 2026",
    viewCount: 2100,
    copyCount: 520,
    isPublished: true,
    isVerified: true,
    status: "Aktif"
  },
  {
    id: "p5",
    title: "Iklan Media Sosial Produk Kecantikan",
    category: "Copywriting",
    description: "Instruksi draf Carousel Instagram peluncuran produk serum pelembab wajah organik.",
    promptText: "Buat draf naskah iklan Instagram Carousel sebanyak 4 slide untuk produk serum pelembab wajah organik baru bernama 'PureGlow'. Slide 1: Hook memikat tentang kulit kusam. Slide 2: Edukasi bahan aktif alami. Slide 3: Testimoni/Hasil nyata 14 hari. Slide 4: Call to action penawaran diskon rilis perdana.",
    imageUrl: "assets/img/beauty-ad.jpg",
    tags: ["instagram", "marketing", "skincare", "carousel"],
    creatorId: "u2",
    creatorName: "Siti Rahma",
    uploadDate: "22 Jan 2026",
    viewCount: 720,
    copyCount: 198,
    isPublished: true,
    isVerified: false,
    status: "Aktif"
  },
  {
    id: "p6",
    title: "Generator Password Aman dengan JavaScript",
    category: "Code",
    description: "Fungsi enkripsi generator sandi kustom dengan proteksi API kriptografi.",
    promptText: "Tulis fungsi JavaScript yang aman untuk membuat password acak dengan panjang tertentu. Fungsi harus menerima parameter panjang password serta opsi untuk menyertakan huruf besar, huruf kecil, angka, dan karakter spesial. Sertakan komentar penjelas yang mendalam tentang keamanan enkripsi Math.random versus crypto.getRandomValues.",
    imageUrl: "assets/img/js-secure-code.jpg",
    tags: ["javascript", "security", "utility", "encryption"],
    creatorId: "u3",
    creatorName: "Budi Santoso",
    uploadDate: "25 Jan 2026",
    viewCount: 1150,
    copyCount: 410,
    isPublished: true,
    isVerified: true,
    status: "Aktif"
  },
  {
    id: "p7",
    title: "UI Kit Dashboard Analitik Modern",
    category: "Design",
    description: "Instruksi visualisasi antarmuka aplikasi pemantauan transaksi berbasis awan.",
    promptText: "Generate a prompt for a modern SaaS analytics dashboard interface UI design on Figma. Clean layout, dark violet accents, frosted glass metrics cards, smooth linear area charts, side navigation panel with active states, clear typography hierarchy, white space, light theme design trends 2026.",
    imageUrl: "assets/img/analytics-ui.jpg",
    tags: ["figma", "dashboard", "uxui", "saas"],
    creatorId: "u1",
    creatorName: "Ahmad Dani",
    uploadDate: "27 Jan 2026",
    viewCount: 1300,
    copyCount: 290,
    isPublished: true,
    isVerified: false,
    status: "Aktif"
  },
  {
    id: "p8",
    title: "Skrip Cinematic Intro Brand",
    category: "Video",
    description: "Format skrip visualisasi berdurasi singkat untuk perkenalan produk kopi lokal.",
    promptText: "Tulis naskah video berdurasi 30 detik untuk intro cinematic sebuah brand kopi lokal premium 'Kopi Swarga'. Naskah harus memuat petunjuk visual (scene by scene), arahan musik/sound effects (SFX), dan naskah voice over (VO) yang menceritakan tentang perjalanan biji kopi dari perkebunan pegunungan hingga cangkir konsumen.",
    imageUrl: "assets/img/cinematic-script.jpg",
    tags: ["cinematic", "storytelling", "coffee", "commercial"],
    creatorId: "u2",
    creatorName: "Siti Rahma",
    uploadDate: "28 Jan 2026",
    viewCount: 480,
    copyCount: 95,
    isPublished: true,
    isVerified: false,
    status: "Aktif"
  },
  {
    id: "p9",
    title: "Email Kampanye Peluncuran Produk Baru",
    category: "Marketing",
    description: "Draf surat penjualan B2B dingin berkonversi tinggi menyasar direktur operasional.",
    promptText: "Buat email marketing dingin (cold email campaign) yang ditujukan kepada manajer operasional untuk menawarkan software otomatisasi alur kerja SaaS. Email harus memiliki baris subjek dengan open-rate tinggi, struktur paragraf yang singkat, menyertakan poin rasa sakit (pain points), bukti sosial singkat, dan ajakan bertindak (CTA) untuk demo 15 menit.",
    imageUrl: "assets/img/email-marketing.jpg",
    tags: ["email", "outreach", "b2b", "sales"],
    creatorId: "u3",
    creatorName: "Budi Santoso",
    uploadDate: "29 Jan 2026",
    viewCount: 610,
    copyCount: 145,
    isPublished: true,
    isVerified: true,
    status: "Aktif"
  }
];
